### ISSUE TITLE
Make notes 2.0 installable via appstore

### ISSUE THREAD

**Issue by RealRancor** [owncloud/notes#185]
Hi,

recently version 2.0 of notes was published at the appstore:

https://apps.owncloud.com/content/show.php/Notes?content=174554

However there are currently two issues:

1) The https://github.com/owncloud/notes/blob/v2.0/appinfo/info.xml is not containing the mandatory:

``<ocsid>174554</ocsid>``

See: https://doc.owncloud.org/server/8.2/developer_manual/app/info.html#ocsid

I think thats the reason why the app is currently not showing up in the oC internal appstore.

2) The download link on the appstore is currently pointing at https://github.com/owncloud/notes/archive/v2.0.zip

This archive contains a folder called ``notes-2.0``. As this folder needs to match the https://github.com/owncloud/notes/blob/v2.0/appinfo/info.xml#L3 the app won't be installable if 1. is solved. The post here: https://github.com/owncloud/core/issues/18116#issuecomment-129445478 contains some pointers how to draft a new release with the correct format needed by the appstore.

**Comment by RealRancor** [comment]
Ah, 1) was already fixed a few days ago: https://github.com/owncloud/notes/commit/de1e67a275ade6ba7f22db628d8b997d41c90a1a

Seems just 2) Needs to be fixed now to fix installing the app (The appstore link is currently pointing to https://github.com/owncloud/notes/archive/v2.0.ztar.gz)

**Comment by Henni** [comment]
I fixed 1) a few hours ago.
I experimented on fixing 2) but couldn't get notes to show up in the oC internal appstore.

**Comment by RealRancor** [comment]
Hi,

thanks :-)

2) should be easily fixable. Try to:

- download https://github.com/owncloud/notes/archive/v2.0.zip
- rename the folder "notes-2.0" in that archive to "notes"
- open https://github.com/owncloud/notes/releases and edit the release
- upload the previous archive to that release
- point the appstore to that new archive

**Comment by Henni** [comment]
@RealRancor are you sure it's .zip and not .tar.gz?
I just uploaded a modified notes-2.0.tar.gz. Maybe you can take a look and give me a hint.

**Comment by RealRancor** [comment]
It might work with tar.gz but definitely works for .zip. Did the same for the polls app:

https://github.com/raduvatav/polls/releases/tag/v0.6.5

**Comment by Henni** [comment]
I followed your instructions, but I can't make it show up...

**Comment by fcturner** [comment]
Hello! Looking forward to this release!

Idea: shouldn't this be ultimately solved by the core installer app, which should work anyway when the folder contains the app name and some version number? Now, each and every app developer has to do this for every single release. This system looks really clumsy at the moment in my opinion...

**Comment by Henni** [comment]
@fcturner I also think that this should be solved in core. But for now we have to fix it here because we want to publish notes to older versions as well.

I would love to see this change in core for the next release (9.0). Feel free to open an issue for this. Otherwise I will do so after this issue is resolved.

**Comment by RealRancor** [comment]
@Henni The release looks right from the app side. So maybe something is missing at the release page on the appstore?

A suggestion / PR to make github archives to work was already available here: https://github.com/owncloud/core/pull/18190 but was denied.

**Comment by RealRancor** [comment]
@Henni Ah, found it. You have a typo in the category (https://doc.owncloud.org/server/8.2/developer_manual/app/info.html#category).

Its "tools" not "tool" in https://github.com/owncloud/notes/blob/v2.0/appinfo/info.xml#L10

**Comment by Henni** [comment]
@RealRancor thanks. But it still doesn't show up. Any further ideas?

**Comment by RealRancor** [comment]
@Henni The app and archive side looks good to me. I have never seen the appstore backend for publishing an app so maybe there is something missing?

**Comment by Henni** [comment]
Any ideas @LukasReschke @DeepDiver1975 ?

**Comment by RealRancor** [comment]
Strange, the same is also happening for tasks: https://github.com/owncloud/tasks/issues/275

**Comment by RealRancor** [comment]
@Henni Not quite sure but this also looks like a typo:

https://github.com/owncloud/notes/blob/v2.0/appinfo/info.xml#L7

According to https://doc.owncloud.org/server/8.2/developer_manual/app/info.html its:

```
<requiremin>8.1</requiremin>
```

**Comment by Henni** [comment]
@RealRancor thanks for all your help so far. I merged your PR but it still isn't fixed.
I really don't understand why this app isn't detected while other apps like Ownnote with a smaller [info.xml](https://github.com/Fmstrat/ownnote/blob/master/appinfo/info.xml) do work.

**Comment by RealRancor** [comment]
@DeepDiver1975 @PVince81 @LukasReschke @VicDeo Could anyone of you help to check whats wrong here? Thnx

**Comment by LukasReschke** [comment]
App was just not marked as approved, see https://github.com/owncloud/app-approval. I approved it for now. Also the version needs to be equally 1:1, so here it would be `2.0.0` and not `2.0`, I fixed that as well.

Appears now at https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=922 and in the "Productivity" secion at ownCloud. Also see https://github.com/owncloud/app-approval

Install worked fine on my 8.2, even though the JS seems broken :question: 

![2016-01-11_20-33-24](https://cloud.githubusercontent.com/assets/878997/12244173/96e7018e-b8a2-11e5-8e58-e8c6e96fe82f.png)

**Comment by RealRancor** [comment]
Thanks!!! Can confirm that the app is now in install able on a oC 8.2 install so closing here for now.
